model: resources/models/0.pt
#model: resources/models/1.pt
#model: runs\detect\train\weights\best.pt

data:
  input_folder: data/input
  output_folder: data/output
  input_file: test2.mp4

detection:
  confidence_threshold: 0.4
  mask_region: [100, 100, 300, 300]

training:
  dataset: data/shared_files_dataset/data.yaml
  device: 0
  epoch: 100

